#include <stdexcept>

using std::runtime_error;

int main() {throw runtime_error("error");}